### ISSUE TITLE
Supporting of experimentGroupId

### ISSUE THREAD

**Issue by kevinkiklee** [WICG/protected-auction-services-discussion#25]
From fledge-docs created by [yanushP](https://github.com/yanushP): privacysandbox/fledge-docs#80  

Hi @chatterjee-priyanka 

Do you planning to support field `experimentGroupId` in B&A code and in request to KeyValue service from BuyerFrontEnd? 
 
Because you docs saying that it will be supported [here](https://github.com/privacysandbox/fledge-docs/blob/999bc459c91ef4bc850d2f78339b083d458a40e9/bidding_auction_services_api.md#buyer-byos-keyvalue-service).
However, I don't see that it's supported in code [here](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/services/common/clients/http_kv_server/buyer/buyer_key_value_async_http_client.h#L38) or [here](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/services/common/clients/http_kv_server/buyer/buyer_key_value_async_http_client.cc#L29C1-L61C1).
At the same time, it's already supported in on-device version, in chromium [here](https://github.com/chromium/chromium/blob/215d235344a022ff753a37791796c06aabb0423f/content/services/auction_worklet/trusted_signals.cc#L377-L381). 

Could you please confirm that this field will be supported in future? The running of experiments it's important for us.

**Comment by akundla-google** [comment]
Released in v3.1.0
