### ISSUE TITLE
JS&Wasm files that needed for bidding.

### ISSUE THREAD

**Issue by yanushP** [WICG/protected-auction-services-discussion#26]
Hi 

I found several fields that I didn't see before documentation of B&A.
I mean fields `protected_app_signals_bidding_js_url ` and `prepare_data_for_ads_retrieval_js_url` that are declare [here](https://github.com/privacysandbox/bidding-auction-servers/blob/main/services/bidding_service/bidding_code_fetch_config.proto#L45-L58)

Also, one of them is used for `AdsRetrievalAsyncHttpClient` that is look like some other [Key Value store](https://github.com/privacysandbox/bidding-auction-servers/blob/b27547a55f20021eb91e1e61b0d2175b4aee02ea/services/common/clients/http_kv_server/buyer/ads_retrieval_async_http_client.h).

Could you please share documentation for what I should use those js files and this Retrieval KV ?

**Comment by chatterjee-priyanka** [comment]
Hi, 

Thanks for reaching out.

This is not for web targeting, but for a specific use-case for app targeting. We expect to publish an explainer documenting that sometime between Jan-March 2024.

**Comment by salmanmlk** [comment]
Hi,

Please check out [this](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_protected_app_signals.md) explainer regarding details about the new protected app signals feature context as well as the fields you asked about in this issue.

Feel free to open another issue if you have more questions. Thank you.
