### ISSUE TITLE
Ad Hoc Meeting - Wed 20th December 2023

### ISSUE THREAD

**Issue by drpaulfarrow** [WICG/protected-auction-services-discussion#35]
We agreed yesterday that most folks would like to have a meeting at the usual time on Wednesday the 20th of December, in addition to those already scheduled, where Microsoft would discuss our B+A implementation. Could you confirm that is happening? Thanks!

**Comment by webmihir** [comment]
Thanks Paul. Would you be able to share the desgn/work done so far here before we setup the meeting, so everyone can familiarize themselves prior to the meeting.

**Comment by drpaulfarrow** [comment]
We will share the pre-read by Tuesday. Thanks for accommodating.
