### ISSUE TITLE
Collect hacker data 

### ISSUE THREAD

**Issue by Baamarm** [WICG/protected-auction-services-discussion#37]
I suggest that you switch to automatic. so that it is easier to get important information. example

**Comment by chatterjee-priyanka** [comment]
Thanks @Baamarm. Would you be able to help us with more information here?

**Comment by Baamarm** [comment]
Can there be no problem ..can you let me know the real issue

**Comment by Baamarm** [comment]
Sekarang saya bersedia untuk berkerja sama

Pada Rab, 20 Dis 2023, 13:50 Priyanka Chatterjee ***@***.***>
menulis:
