### ISSUE TITLE
Region specific requirements for KMS

### ISSUE THREAD

**Issue by kapilvgit** [WICG/protected-auction-services-discussion#42]
Can you clarify if there are any region-specific requirements for the KMS? In a previous discussion, there was a mention of a requirement that KMS needs to generate different keys for different regions.

**Comment by hostirosti** [comment]
Hi Kapil,

currently keys are served globally and we do not create region specific / geo-fenced keys.

**Comment by kapilvgit** [comment]
Thanks for the clarification.
