### ISSUE TITLE
Support for buyerAndSellerReportingId on B&A

### ISSUE THREAD

**Issue by rashmijrao** [WICG/protected-auction-services-discussion#57]
Hello,

buyerAndSellerReportingId is available as a part of [interest group attributes](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#12-interest-group-attributes) and is passed as an input to [reportResult()](https://wicg.github.io/turtledove/#dom-reportingbrowsersignals-buyerandsellerreportingid) if present for on-device auctions. We are seeking feedback on the priority to support buyerAndSellerReportingId on B&A. If buyerAndSellerReportingId is not present in reportResult() or if IG name is not replaced by buyerAndSellerReportingId in reportWin() would this break the processing of reporting pings? Is there a timeline by which buyerAndSellerReportingId is expected to be supported?
We have a proposal to support buyerAndSellerReportingId on B&A that will be published in the [event level reporting explainer](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_event_level_reporting.md):
The buyerAndSellerReportingId can be generated by the AdTechs in the generateBid() script and embed it in the "[ad](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_api.md#generatebid)" object which is returned in the response. This can be passed all the way to the reporting scripts.
Please let us know if there is any concerns with this approach.

Regards
Rashmi

**Comment by rashmijrao** [comment]
@maciejkowalczyk @thegreatfatzby

**Comment by maciejkowalczyk** [comment]
I think returning `buyerAndSellerReportingId`/`buyerReportingId` from `generateBid` on B&A looks fine.
However, I'd use top-level fields in the response and leave the opaque `ad` object for ad metadata passed from `generateBid` to `scoreAd`

**Comment by rashmijrao** [comment]
We are considering these advantages to return the `buyerReportingId`/`buyerAndSellerReportingId` in `ad` object from `generateBid` response:
- This will simplify the APIs(no change needed in GenerateBidResponse/ScoreAdsRequest to pass this id to Auction Service). 
- This would be in parity with the [`ads`](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#12-interest-group-attributes) object on Chrome which contains the `buyerReportingId`/`buyerAndSellerReportingId`.  The [`ads`](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#12-interest-group-attributes) object contains the `metadata` field which is already supported on B&A in the `ad` returned from `generateBid`. 

@maciejkowalczyk Could you please let us know if there are any cons/concerns with this approach?

**Comment by rashmijrao** [comment]
We are going with the option to return the buyerReportingId in the `ad` object considering the marginal difference in benchmark results.

**Comment by maciejkowalczyk** [comment]
Perhaps you could still reconsider this decision:
* As a side effect of putting into the `ad` object, `buyerReportingId` would be visible in `scoreAd` `adMetadata` parameter, which is undesirable.
*  This would be inconsistent with Chrome's behaviour.
*  IIUC, the `ad` object returned from `generateBid` is not related to the `metadata` field of an ad in IG.
Both are *opaque* JSON-serializable values, but the former is a contract between buyer and seller, while the latter is private to buyer.

**Comment by rashmijrao** [comment]
The proposal we have is to add a new struct field for  `buyerReportingId`/`buyerAndSellerReportingId` in the `ad` object. Currently, this object is parsed in the Auction Service and only the value for `metadata` is sent as input to `scoreAds()` : https://github.com/privacysandbox/bidding-auction-servers/blob/64cf212087572e4f0c1eac56083e49489d85e06a/services/auction_service/utils/proto_utils.h#L134. The whole `ad` object is not passed to `scoreAds()`. Similarly, we plan to get the value for `buyerReportingId`/`buyerAndSellerReportingId` from the object. So `buyerReportingId` would not be available to `scoreAd()`. We are considering this approach mainly based on the difference in latency after running microbenchmark tests.

**Comment by rashmijrao** [comment]
Thank you for pointing out the concerns with passing the buyer_reporting_id in the `ad` object. [B&A expects the `ad` object to be a json with a sub field called `metadata` ](https://github.com/privacysandbox/bidding-auction-servers/blob/64cf212087572e4f0c1eac56083e49489d85e06a/services/auction_service/utils/proto_utils.h#L135)and our initial proposal was to introduce another sub field called `buyerReportingId`. The whole `ad` object itself is not being passed to `scoreAd()` in B&A currently. This seems be a disparity in the way on-device/AdTechs expect this object be handled. We are working on a fix to set the `ad` as it is in the `ad_metadata` input to `scoreAd()`.
So the buyer_reporting_id will be supported as a top level field in the `generateBid()` response.
