### ISSUE TITLE
Agenda items for Bidding&Auction Service - TPAC 2024

### ISSUE THREAD

**Issue by fhoering** [WICG/protected-auction-services-discussion#85]
@michaelkleber @thegreatfatzby @bjschnei @peiwenhu @akshaypundle, @itaysharfi and members of the WICG

I'd like to suggest adding on the following topics, as part of a WICG - B&A service sessions at TPAC:
- Criteo benchmarking results (https://github.com/privacysandbox/protected-auction-key-value-service/issues/43#issuecomment-2218079475)
- Define common benchmarking methodology
- ROMA BYOB (https://github.com/privacysandbox/data-plane-shared-libraries/blob/main/docs/roma/roma_byob.md, https://github.com/WICG/protected-auction-services-discussion/issues/83, https://github.com/privacysandbox/protected-auction-key-value-service/issues/66)
- Datastructures for caching/storage (https://github.com/WICG/protected-auction-services-discussion/issues/81, https://github.com/privacysandbox/protected-auction-key-value-service/issues/62)

Would you be interested in that?
Should we reserve a slot in https://github.com/WICG/admin/issues/194 ?

**Comment by yhkumargoogle** [comment]
@fhoering Do you want to discuss this in tomorrow's WICG call ?
https://github.com/WICG/protected-auction-services-discussion/issues/27

**Comment by fhoering** [comment]
Yes. I added it to the agenda items.

**Comment by yhkumargoogle** [comment]
Understood. I have updated the agenda to reflect this.

**Comment by fhoering** [comment]
Closing. has been discussed here:

https://github.com/WICG/privacy-preserving-ads/blob/main/Open%20Discussions/20240924-WICG_TPAC_Criteo_OnDeviceVsServerSide.pdf
https://github.com/WICG/privacy-preserving-ads/blob/main/Open%20Discussions/2024-09-24-tpac.md

**Comment by yhkumargoogle** [comment]
@fhoering As discussed on Sep 11, we had added the following to the agenda for today (Oct 9)
- Criteo benchmarking results (Performance of triggering UDF execution engine [privacysandbox/protected-auction-key-value-service#43](https://github.com/privacysandbox/protected-auction-key-value-service/issues/43) (comment))
- Define common benchmarking methodology

But we dismissed the session as you were not available on the call. Do you want to discuss this on the next call (Oct 23)?

**Comment by fhoering** [comment]
I presented some of the benchmarks here:
https://github.com/WICG/privacy-preserving-ads/blob/main/Open%20Discussions/20240924-WICG_TPAC_Criteo_OnDeviceVsServerSide.pdf

If you think this is still of interest I can present them in the next meeting yes.

On the common benchmarking methodology I have not much to discuss yet beyond saying that I think it is important for several reasons in particular given RTB constraints and given several factors that can significantly increase the cloud infrastructure cost. 

Potentially, as a next step, someone from Google could present what has been done, the features this supports, how to start using this and the next steps on how to simplify those tools and make them more generic
- https://github.com/privacysandbox/protected-auction-key-value-service/tree/release-0.17/tools/benchmarking
- https://github.com/privacysandbox/bidding-auction-servers/tree/main/tools/load_testing
- https://github.com/privacysandbox/data-plane-shared-libraries/tree/main/src/roma/benchmark
- https://github.com/privacysandbox/data-plane-shared-libraries/blob/main/docs/roma/byob/Benchmarking.md

What do you think ?

**Comment by yhkumargoogle** [comment]
@fhoering I have added it to the [agenda](https://docs.google.com/document/d/1Hk6uW-i4KPUb-u20E-EWbu8_EbPnzcptnhV9mxBP5Mo/edit?tab=t.0#heading=h.sk9ofyi8husf) for Nov 6.

**Comment by fhoering** [comment]
Ok. Thanks. If it is possible rather then a discussion it could be useful also to have a presentation/overview on the existing benchmarking tools, what they allow to do and how to use them. I could add more people also on Criteo side to attend.

**Comment by yhkumargoogle** [comment]
@fhoering We wanted to discuss https://github.com/privacysandbox/protected-auction-key-value-service/issues/72 asap. So, we would like to use the Nov 6 meeting for it.

Can we discuss this in the following session?

**Comment by fhoering** [comment]
Yes. no problem.

**Comment by fhoering** [comment]
@yhkumargoogle I prepared an updated presentation for tomorrow.

**Comment by yhkumargoogle** [comment]
@fhoering Unfortunately, we have to cancel tomorrow as several individuals cannot make it. I have added this topic along with https://github.com/privacysandbox/bidding-auction-servers/issues/23 to the [agenda](https://docs.google.com/document/d/1Hk6uW-i4KPUb-u20E-EWbu8_EbPnzcptnhV9mxBP5Mo/edit?tab=t.0#heading=h.sk9ofyi8husf) for Dec 4.
